---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard-ingress-cert
  namespace: istio-system
spec:
  secretName: wildcard-ingress-cert
  dnsNames:
    - "*.c0.kube8.ga"
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  commonName: "*.c0.kube8.ga"

